### ISSUE TITLE
applecar

### ISSUE THREAD

**Issue by arthurlang** [flexih/WatchAppList#1]
您是从三方app列表查到的数据吗？要是想知道applecar等等的应用有多少该怎么写shell脚本呢？

**Comment by flexih** [comment]
数据来自七麦数据。你是说一个app是否支持car play？

**Comment by arthurlang** [comment]
car  play上的app排行榜，shell脚本写得特别棒

**Comment by flexih** [comment]
应该爬不到数据。但是可以把ipa下载下来，看看linked framewrok里有没有Carplay.framework，有的话就是支持Car Play。
